---
title: "EP16: Missing Values in Clinical Research: Multiple Imputation"
subtitle: "Summary I"
author: "Nicole Erler"
institute: "Department of Biostatistics, Erasmus Medical Center"
date: ""
email: "n.erler@erasmusmc.nl"
output:
  beamer_presentation:
    keep_tex: false
    template: mytemplate.latex
    includes:
      in_header: [SlideTemplate.tex, defs.tex]
    incremental: false
classoption: [aspectratio=169]
bibliography: references.bib
---

```{r setup, include = FALSE}
projdir <- gsub("/Slides", "", getwd())

knitr::knit_hooks$set(
  nospace = function(before, options, envir) {
    if (before) {
      knitr::asis_output("\\vspace*{-1.5ex}")
    }
  }
)


knitr::opts_chunk$set(echo = TRUE, nospace = TRUE, nospaceafter = TRUE,
                      fig.align = 'center', out.width = "100%")

```


## Summary
\blue{1. What is Multiple Imputation?}\
\begin{itemize}
\item Rubin's \blue{idea}:
      \begin{itemize}
      \item Missing values need to be represented by \blue{multiple imputed values}.
      \item A \blue{model is necessary} to obtain good imputations.
      \end{itemize}
\item Imputed values are obtained from the \blue{predictive distribution} of the missing data,
given the observed data.
\item Multiple completed datasets are created from the multiple imputed values.
\item Multiple imputation has \blue{three steps:}\
      \blue{imputation, analysis, pooling}
\end{itemize}

## Summary
\blue{2. Imputation step}
\begin{itemize}
\item Two \blue{sources of variation}:
      \begin{itemize}
      \item \blue{parameter uncertainty}
      \item \blue{random variation}
      \end{itemize}
\item \blue{Two approaches} to MI for imputation of non-monotone multivariate missing data
      \begin{itemize}
      \item \blue{MICE/FCS}
      \item \blue{Joint model imputation}
      \end{itemize}
\item The MICE algorithm re-uses univariate imputation models by iterating
      through all incomplete variables, multiple times (\blue{iterations})
\item \blue{Multiple runs} through the algorithm are necessary to create multiple
      imputed datasets
\item The \blue{convergence of the chains} needs to be checked.
\end{itemize}


## Summary
\blue{3. Analysis step}
\begin{itemize}
\item Analyse each imputed dataset the way you would analyse a complete dataset
\end{itemize}


\blue{4. Pooling}
\begin{itemize}
\item Results from analyses of multiple imputed datasets can be summarized
      by taking the \blue{average of the regression coefficients}
\item For the total variance, \blue{three sources of variation} need to be considered:
      \begin{itemize}
      \item \blue{within imputation variance}
      \item \blue{between imputation variance}
      \item uncertainty due to finite number of imputations
      \end{itemize}
\end{itemize}


## Summary
\blue{5. A closer look at the imputation step}
\begin{itemize}
\item Two \blue{parametric approaches} for imputation:
      \begin{itemize}
      \item \blue{Bayesian} (sample from posterior distribution of parameters)
      \item \blue{Bootstrap} (uses bootstrap samples of the data to estimate parameters)
      \end{itemize}
\item \blue{Predictive mean matching} is a semi-parametric alternative\\
      (it matches observed and missing cases based on their predicted values).
\item In PMM we need to consider
      \begin{itemize}
      \item \blue{donor selection}
      \item \blue{matching type} (how parameters are sampled/estimated),
      \item the \blue{set of data} used to calculate/estimate the parameters.
      \end{itemize}
\item Bayesian and bootstrap imputation take into account the variation, while
      many \blue{choices in PMM lead to underestimation of the variation}.
\end{itemize}


## Summary
\blue{6. Know your data}\
Check the
\begin{itemize}
\item missing data pattern
\item distribution of observed values
\item associations \& patterns in the observed values
\end{itemize}

\vspace*{3ex}

\begin{itemize}
\item Think about why values are missing. Is MAR reasonable?
\item Is additional information available (auxiliary variables)?
\end{itemize}

\framebreak
----------------------------------------

\blue{7. Imputation with mice}\
Specification of
\begin{itemize}
\item imputation method
\item predictor matrix
\item visit sequence
\end{itemize}

\vspace*{3ex}

Further tailoring of the imputation using
\begin{itemize}
\item passive imputation
\item post processing
\end{itemize}

----------------------------------------
\framebreak

\blue{8. Convergence \& diagnostics}
\begin{itemize}
\item Logged events
\item convergence: traceplots
\item distribution of observed and imputed values (conditional on other variables)\\
\end{itemize}


\blue{9. Analysis \& pooling}
\begin{itemize}
\item \textbf{mice} functions `with()`{.R} and `pool()`{.R}
\item alternative pooling using \textbf{mitools}
\item additional functions in \textbf{mice}: `pool.r.squared()`{.R}, `pool.compare()`{.R}
\item additional functions in other packages: `miceadds::micombine.chisquare()`{.R},
`miceadds::micombine.F()`{.R}
\end{itemize}

----------------------------------------
\framebreak

\blue{10. Additional functions in mice}
\begin{itemize}
\item `complete()`{.R}, `mids2spss()`{.R}
\item `ibind()`{.R}, `cbind.mids()`{.R}
\end{itemize}


----------------------------------------
\framebreak
\begin{itemize}
\item MICE requires \blue{congenial \& compatible imputation models} to work well.
\item When this is not the case, (naive) use of MICE can lead to \blue{biased results}.
\item Common settings that require special attention are
      \begin{itemize}
      \item \blue{non-linear functional forms \& interaction terms}
      \item \blue{longitudinal data}
      \item \blue{survival data}
      \end{itemize}
\end{itemize}

----------------------------------------
\framebreak

\begin{itemize}
\item When using the package \textbf{mice}, there are choices that can \blue{reduce bias}
      \begin{itemize}
      \item %\Rarg{pmm} tends to be less biased than \Rarg{norm} for interactions or non-linear associations
      \item JAV approach reduces bias in settings with interactions or non-linear associations
      \item \blue{special 2-level imputation methods} are available for longitudinal data
      \item The \blue{Nelson-Aalen estimator} can be used instead of the time variable
            for imputing survival data when effects are not too large.
      \end{itemize}
\item Generally, \blue{problems} are more severe when
      \begin{itemize}
      \item \blue{proportions of missing values are large},
      \item effect sizes are large,
      \item little other \blue{covariate information} is available.
      \end{itemize}
      (Note that in the examples we had all of the above.)
\end{itemize}

----------------------------------------
\framebreak

\begin{itemize}
\item In settings where MICE may not provide valid imputations,
      \blue{alternative approaches} are available and should be considered.
\item R packages that provide such alternative approaches are for example:
      \begin{itemize}
      \item \blue{JointAI} (non-linear, longitudinal \& survival)
      \item \blue{smcfcs} (non-linear \& survival)
      \item \blue{jomo} (non-linear, longitudinal \& survival)
      \end{itemize}
\item These packages are very young.
      \begin{itemize}
      \item Hence, they may still have some problems.\\
            \blue{\ding{225}} \blue{Use them carefully!} (and email the maintainer about problems)
      \item They are under \blue{active development}, so resolutions of bugs and
      features are frequently added.
      \end{itemize}
\end{itemize}

